/*  Vytvorenie tabulky T_PERSON */
CREATE TABLE T_PERSON
(
	ID 		      SERIAL 		    PRIMARY KEY,
	NICK		    VARCHAR(50) 	NOT NULL UNIQUE,
	PASSWORD	  VARCHAR(255) 	NOT NULL,
	ID_ADDRESS	BIGINT
);

/* Vytvorenie tabulky T_ADDRESS */
CREATE TABLE T_ADDRESS (
	ID          SERIAL 		    PRIMARY KEY,
	STREET	    VARCHAR(255) 	NOT NULL,
	TOWN	      VARCHAR(255) 	NOT NULL,
	STATE	      VARCHAR(255) 	NOT NULL,
	ZIP	        VARCHAR(20)   NOT NULL
);

/* Vytvorenie tabulky T_CONTACT */
CREATE TABLE T_CONTACT (
	ID 		      SERIAL 		    PRIMARY KEY,
	NAME		    VARCHAR(255)	NOT NULL UNIQUE,
	VALUE 	    VARCHAR(255)	NOT NULL,
	TYPE		    VARCHAR(255)	NOT NULL,
	DESCRIPTION	VARCHAR(1000) NOT NULL DEFAULT '',
	ID_PERSON 	BIGINT 		    NOT NULL
);

/* Vytvorenie tabulky T_GROUP */
CREATE TABLE T_GROUP (
	ID 		        SERIAL 		      PRIMARY KEY,
	NAME 		      VARCHAR(255)	  NOT NULL UNIQUE,
	VALUE		      VARCHAR(255)	  NOT NULL,
	DESCRIPTION 	VARCHAR(1000) 	NOT NULL DEFAULT ''
);

/* Vytvorenie tabulky T_ACCESS */
CREATE TABLE T_ACCESS (
	ID 		          SERIAL 	PRIMARY KEY,
	CREATE_ACCESS   BOOLEAN NOT NULL DEFAULT FALSE,
	DELETE_ACCESS   BOOLEAN NOT NULL DEFAULT FALSE,
	UPDATE_ACCESS   BOOLEAN	NOT NULL DEFAULT FALSE,
	READ_ACCESS	    BOOLEAN NOT NULL DEFAULT FALSE
);

/* Vytvorenie tabulky T_PERSON_ACCESS */
CREATE TABLE T_PERSON_ACCESS (
	ID 		      SERIAL 	PRIMARY KEY,
	ID_PERSON 	BIGINT 	NOT NULL,
	ID_ACCESS 	BIGINT 	NOT NULL,
	CREATED 	  DATE 	  NOT NULL DEFAULT NOW(),
	MODIFIED	  DATE
);

/* Vytvorenie tabulky T_PERSON_GROUP */
CREATE TABLE T_PERSON_GROUP (
	ID 		    SERIAL 	PRIMARY KEY,
	ID_GROUP 	BIGINT 	NOT NULL,
	ID_ACCESS BIGINT 	NOT NULL,
	ID_PERSON	BIGINT 	NOT NULL,
	CREATED 	DATE 	  NOT NULL DEFAULT NOW(),
	MODIFIED	DATE
);

/* Vytvorenie tabulky T_DOCUMENT */
CREATE TABLE T_DOCUMENT (
	ID 		          SERIAL 		    PRIMARY KEY,
	ID_AUTHOR	      BIGINT 		    NOT NULL,
	ID_CHIEF_EDITOR	BIGINT 		    NOT NULL,
	TITLE		        VARCHAR(50) 	NOT NULL,
	ABSTRACT	      VARCHAR(255) 	NOT NULL DEFAULT '',
	CREATED		      DATE 		      NOT NULL DEFAULT NOW(),
	MODIFIED	      DATE		      ,
	EXPIRATED 	    DATE 		      ,
	MODIFIED_BY	    BIGINT	    	,
	LINK		        VARCHAR(255) 	NOT NULL DEFAULT ''
);

/* Vytvorenie tabulky T_DOCUMENT_ACCESS */
CREATE TABLE T_DOCUMENT_ACCESS (
      ID 		      SERIAL PRIMARY KEY,
	ID_DOCUMENT	    BIGINT NOT NULL,
	ID_ACCESS	      BIGINT NOT NULL
);

/* Vytvorenie tabulky T_DOCUMENT_TYPE */
CREATE TABLE T_DOCUMENT_TYPE (
	ID 		        SERIAL        PRIMARY KEY,
	NAME		      VARCHAR(50)   NOT NULL,
	VALUE 		    VARCHAR(255)  NOT NULL,
	DESCRIPTION	  VARCHAR(1000)	NOT NULL DEFAULT ''
);

/* Vytvorenie tabulky T_DOCUMENT_TYPE_ACCESS */
CREATE TABLE T_DOCUMENT_TYPE_ACCESS (
	ID 			          SERIAL PRIMARY KEY,
	ID_DOCUMENT_TYPE 	BIGINT NOT NULL,
	ID_ACCESS		      BIGINT NOT NULL
);

-- ---------------------------------------------------------
--
-- Vytvorenie vezieb medzi tabulkami
--
-- ---------------------------------------------------------
ALTER TABLE T_PERSON
	ADD CONSTRAINT FK_PERSON_ADDRESS 
	FOREIGN KEY(ID_ADDRESS) REFERENCES T_ADDRESS;

ALTER TABLE T_CONTACT
	ADD CONSTRAINT FK_CONTACT_PERSON
	FOREIGN KEY(ID_PERSON) REFERENCES T_PERSON;

ALTER TABLE T_DOCUMENT
	ADD CONSTRAINT FK_DOCUMENT_PERSON
	FOREIGN KEY(ID_CHIEF_EDITOR) REFERENCES T_PERSON;

ALTER TABLE T_DOCUMENT
	ADD CONSTRAINT FK_DOCUMENT_MODIFIED 
	FOREIGN KEY(MODIFIED_BY) REFERENCES T_PERSON;

ALTER TABLE T_DOCUMENT
	ADD CONSTRAINT FK_DOCUMENT_AUTHOR
	FOREIGN KEY(ID_AUTHOR) REFERENCES T_PERSON;

ALTER TABLE T_PERSON_ACCESS
	ADD CONSTRAINT FK_PACCESS_ACCESS
	FOREIGN KEY(ID_ACCESS) REFERENCES T_ACCESS;

ALTER TABLE T_PERSON_ACCESS
	ADD CONSTRAINT FK_PACCESS_PERSON 
	FOREIGN KEY(ID_PERSON) REFERENCES T_PERSON;

ALTER TABLE T_PERSON_GROUP
	ADD CONSTRAINT FK_PGROUP_ACCESS
	FOREIGN KEY(ID_ACCESS) REFERENCES T_ACCESS;

ALTER TABLE T_PERSON_GROUP
	ADD CONSTRAINT FK_PGROUP_GROUP
	FOREIGN KEY(ID_GROUP) REFERENCES T_GROUP;

ALTER TABLE T_PERSON_GROUP
	ADD CONSTRAINT FK_PGROUP_PERSON
	FOREIGN KEY(ID_PERSON) REFERENCES T_PERSON;

ALTER TABLE T_DOCUMENT_ACCESS
	ADD CONSTRAINT FK_DACCESS_ACCESS 
	FOREIGN KEY(ID_ACCESS) REFERENCES T_ACCESS;

ALTER TABLE T_DOCUMENT_ACCESS
	ADD CONSTRAINT FK_DACCESS_DOCUMENT
	FOREIGN KEY(ID_DOCUMENT) REFERENCES T_DOCUMENT;

ALTER TABLE T_DOCUMENT_TYPE_ACCESS
	ADD CONSTRAINT FK_DTACCESS_ACCESS
	FOREIGN KEY(ID_ACCESS) REFERENCES T_ACCESS;

ALTER TABLE T_DOCUMENT_TYPE_ACCESS
	ADD CONSTRAINT FK_DTACCESS_DTYPE
	FOREIGN KEY(ID_DOCUMENT_TYPE) REFERENCES T_DOCUMENT_TYPE;
